/*
 * WARNING: Automatically copied from dga-tools
 */

pipeline {
  agent {
    docker {
      image 'dga-tools:latest'
      args '--volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp:/tmp'
    }
  }

  triggers {
    pollSCM( '* 22,23,0-8 * * 0-5')
    cron( 'H H(2-3) * * H(2-4)') // UTC About Midday Sydney time on a workday.
  }

  options {
    timeout(time: 1, unit: 'HOURS')
    disableConcurrentBuilds()
    parallelsAlwaysFailFast()
  }

  stages {
    stage('Build') {

      steps {
        sh '''\
          #!/bin/bash
          set -ex

          /home/tools/build.sh
          /home/tools/push.sh
        '''.stripIndent()
      }
    }

    stage('QA') {
      parallel {
        stage('validate') {

          steps {
            sh '''\
              #!/bin/bash
              set -ex

              /home/tools/pull.sh
              /home/tools/run.sh --require 3.5 --mode validate
            '''.stripIndent()
          }
        }

        stage('CVE scan') {
          when { anyOf { branch 'Develop'; changeRequest target: 'Develop' } }

          steps {
            script {
              try {
                sh '''\
                  #!/bin/bash
                  set -ex

                  /home/tools/cve-scan.sh
                '''.stripIndent()
                env.CVE_SCAN_FAILED = false
              }
              catch (err) {
                echo "Caught: ${err}"
                env.CVE_SCAN_FAILED = true
              }
            }
          }
          post {
            always {
              archiveArtifacts artifacts: 'cve-scan.json', fingerprint: true
            }
          }
        }
      }
    }

    stage('Prompt') {
      agent none
      when { expression { env.CVE_SCAN_FAILED == 'true' } }
      steps {
        script {
          timeout(time: 15, unit: 'MINUTES') {
            input( message: 'CVE scan detected issues', ok: 'Continue?')
          }
        }
      }
    }

    stage('Release') {
      when {
        environment name: 'CHANGE_ID', value: ''
      }

      steps {
        sh '''\
          #!/bin/bash
          set -ex

          /home/tools/release.sh
        '''.stripIndent()
      }
    }
  }
  post {
    cleanup {
      
      steps {
        sh '''\
          #!/bin/bash
          set -ex

          /home/tools/clean-up.sh
        '''.stripIndent()
      }
    }
  }
}
